import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { Button, Text, Title } from '@mantine/core';
import styles from '../styles/Home.module.css';
import { useMantineTheme } from '@mantine/core';

export default function Home(props) {

console.log(props)
  const theme = useMantineTheme();
  console.log(theme)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title order={1}>
          this will gonna be the title of the blog which will help you rich and
          reach where you wanna go.{" "}
        </Title>
      </main>
    </div>
  );
}
